### ISSUE TITLE
Error installing v1.4.0 in High Sierra

### ISSUE THREAD

**Issue by lifepillar** [gerbera/homebrew-gerbera#20]
Is v1.4.0 supposed to build in High Sierra? I am using macOS 10.13.6 and Xcode 10.1, and `brew install gerbera` fails with these errors:

```
[ 99%] Building CXX object CMakeFiles/libgerbera.dir/src/zmm/strings.cc.o
/usr/bin/clang++  -DATRAILERS -DHAVE_AVSTREAM_CODECPAR -DHAVE_CURL -DHAVE_FFMPEG -DHAVE_FFMPEGTHUMBNAILER -DHAVE_JS -DHAVE_LIBEXIF -DHAVE_MAGIC -DHAVE_MATROSKA -DHAVE_NL_LANGINFO -DHAVE_SETLOCALE -DHAVE_SQLITE3 -DHAVE_TAGLIB -DONLINE_SERVICES -DPACKAGE_DATADIR=\"/usr/local/Cellar/gerbera/1.4.0/share/gerbera\" -DPACKAGE_NAME=\"Gerbera\" -DSOPCAST -DTOMBDEBUG -DUPNP_HAS_EXTRA_HEADERS_LIST -DVERSION=\"1.4.0\" -D__FILENAME__=\"src/zmm/strings.cc\" -I/tmp/gerbera-20200202-5613-1n3nesc/gerbera-1.4.0/src -I/usr/local/include/upnp -I/usr/local/opt/sqlite/include -I/usr/local/include/libexif -I/usr/local/include/ebml -I/usr/local/include/matroska  "-stdlib=libc++" -Wall -stdlib=libc++ -DNDEBUG   -std=c++1z -o CMakeFiles/libgerbera.dir/src/zmm/strings.cc.o -c /tmp/gerbera-20200202-5613-1n3nesc/gerbera-1.4.0/src/zmm/strings.cc
/tmp/gerbera-20200202-5613-1n3nesc/gerbera-1.4.0/src/zmm/strings.cc:278:40: error: call to unavailable member function 'value': introduced in macOS 10.14
        auto base = new StringBase(str.value().c_str(), str.value().length());
                                   ~~~~^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:933:33: note: candidate function has been explicitly made unavailable
    constexpr value_type const& value() const&
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:942:27: note: candidate function not viable: 'this' argument has type 'const std::optional<std::string>' (aka 'const optional<basic_string<char, char_traits<char>, allocator<char> > >'), but method is not marked const
    constexpr value_type& value() &
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:951:28: note: candidate function not viable: 'this' argument has type 'const std::optional<std::string>' (aka 'const optional<basic_string<char, char_traits<char>, allocator<char> > >'), but method is not marked const
    constexpr value_type&& value() &&
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:960:34: note: candidate function not viable: no known conversion from 'const optional<...>' to 'const optional<...>' for object argument
    constexpr value_type const&& value() const&&
                                 ^
/tmp/gerbera-20200202-5613-1n3nesc/gerbera-1.4.0/src/zmm/strings.cc:278:61: error: call to unavailable member function 'value': introduced in macOS 10.14
        auto base = new StringBase(str.value().c_str(), str.value().length());
                                                        ~~~~^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:933:33: note: candidate function has been explicitly made unavailable
    constexpr value_type const& value() const&
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:942:27: note: candidate function not viable: 'this' argument has type 'const std::optional<std::string>' (aka 'const optional<basic_string<char, char_traits<char>, allocator<char> > >'), but method is not marked const
    constexpr value_type& value() &
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:951:28: note: candidate function not viable: 'this' argument has type 'const std::optional<std::string>' (aka 'const optional<basic_string<char, char_traits<char>, allocator<char> > >'), but method is not marked const
    constexpr value_type&& value() &&
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/optional:960:34: note: candidate function not viable: no known conversion from 'const optional<...>' to 'const optional<...>' for object argument
    constexpr value_type const&& value() const&&
                                 ^
2 errors generated.
```

**Comment by whyman** [comment]
Thanks for reporting!

Fun Apple stuff going on here...

It seems an intentional breakage on the Apple side to encourage the upgrade of Mojave. Official LLVM (which can be installed by brew) will be fine.

🤷‍♀️

**Comment by whyman** [comment]
Going to close this as there is not much we can do from our side :-1:

**Comment by lifepillar** [comment]
Thanks. I'll try to build with LLVM from Homebrew then.
